version: '3'
services: 
    angularnginx:
        build: angular
        ports:
         - 80:80
    nodeservice:
        build: server
        ports: 
         - 3000:3000
        links: 
         - mongodb
    mongodb:
        image: mongo
        ports:
         - 27017:27017
        environment:
         - MONGO_INITDB_ROOT_USERNAME=admin                
         - MONGO_INITDB_ROOT_PASSWORD=password